name: site
recipe: drupal10

services:
  appserver:
    type: php:8.1
    via: nginx
    config:
      php: .lando/php.ini
  database:
    type: mariadb:10.4
    app_mount: disabled
    overrides:
      image: bitnami/mariadb:10.4
  cache:
    app_mount: disabled
    type: redis:7

tooling:
  drush:
    service: appserver
    cmd: /app/vendor/bin/drush
  drupal:
    service: appserver
    cmd: /app/vendor/bin/drupal
  phpunit:
    service: appserver
    cmd: /app/vendor/bin/phpunit
  redis-cli:
    service: cache

config:
  webroot: web
  via: nginx
